package leetcode.legostin.hash_table

/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 */
class FindTheDifference {

    fun findTheDifference(s: String, t: String): Char {
        val occurrence = IntArray(28)

        for (i in s.toCharArray()) {
            occurrence[i.code - 'a'.code] += 1
        }
        for (i in t.toCharArray()) {
            var count = occurrence[i.code - 'a'.code]
            count--
            if (count < 0) {
                return i
            }
            occurrence[i.code - 'a'.code] = count
        }
        // not found
        return 'a'
    }
}
